name = "Synixe Pictures"
prefix = "synixe_pictures"
mainprefix = "x"
author = "Synixe Contractors"

[files]
include = [
    "synixe_x64.dll",
]

[hemtt.launch.default]
workshop = [
    "450814997", # CBA
    "463939057", # ACE3
    "1779063631", # Zeus Enhanced
]
dlc = [
    "ws",
    "rf",
]

[hemtt.launch.aegis]
extends = "default"
workshop = [
    "2538332070", # Aegis - Development
    "2538339575", # Atlas - Development
    "2538342230", # Opposing Forces - Development
    "2402219547", # Theseus
    "2684335735", # Revolución
    "3302425224", # JCA MP5
]

[hemtt.launch.mgp]
extends = "default"
workshop = [
    "2871002081" # Mil Gear Pack - Simpel
]

[hemtt.launch.adt]
extends = "default"
workshop = [
    "2369477168", # ADT
]

[hemtt.launch.sma]
extends = "default"
workshop = [
    "2983059191", # SMA Optics
]

[hemtt.launch.theseus]
extends = "default"
workshop = [
    "646999497" # Theseus Services
]

[hemtt.launch.gorkas]
extends = "default"
workshop = [
    "2752324758" # Gorkas 'n' Gear
]
